// <auto-generated />
using Helthy_Shop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Helthy_Shop.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20250320201813_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DietDish", b =>
                {
                    b.Property<int>("Dishesid")
                        .HasColumnType("int");

                    b.Property<int>("Tagsid")
                        .HasColumnType("int");

                    b.HasKey("Dishesid", "Tagsid");

                    b.HasIndex("Tagsid");

                    b.ToTable("DishDiets");
                });

            modelBuilder.Entity("Helthy_Shop.Data.Models.Diet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("dietName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Diet");
                });

            modelBuilder.Entity("Helthy_Shop.Data.Models.Dish", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("allergens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("calories")
                        .HasColumnType("int");

                    b.Property<string>("composition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mealID")
                        .HasColumnType("int");

                    b.Property<string>("micronutrients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("mealID");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("Helthy_Shop.Data.Models.Meal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("mealName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Meal");
                });

            modelBuilder.Entity("DietDish", b =>
                {
                    b.HasOne("Helthy_Shop.Data.Models.Dish", null)
                        .WithMany()
                        .HasForeignKey("Dishesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helthy_Shop.Data.Models.Diet", null)
                        .WithMany()
                        .HasForeignKey("Tagsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helthy_Shop.Data.Models.Dish", b =>
                {
                    b.HasOne("Helthy_Shop.Data.Models.Meal", "Meal")
                        .WithMany("dishs")
                        .HasForeignKey("mealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Helthy_Shop.Data.Models.Meal", b =>
                {
                    b.Navigation("dishs");
                });
#pragma warning restore 612, 618
        }
    }
}
